simfin:
  apiKey: $ORACULUM_HARVESTER_SIMFIN_API_KEY
  chunkSize: $ORACULUM_HARVESTER_SIMFIN_CHUNK_SIZE|500000
  refreshDays: $ORACULUM_HARVESTER_SIMFIN_REFRESH_DAYS|1

alphaVantage:
  apiUrl: https://www.alphavantage.co
  apiKey: $ORACULUM_HARVESTER_ALPHA_VANTAGE_API_KEY

kafka:
  brokers: $ORACULUM_HARVESTER_KAFKA_BROKERS
  topics:
    market: $ORACULUM_HARVESTER_KAFKA_TOPIC_MARKET|oraculum.market
    industry: $ORACULUM_HARVESTER_KAFKA_TOPIC_INDUSTRY|oraculum.industry
    news: $ORACULUM_HARVESTER_KAFKA_TOPIC_NEWS|oraculum.news
    dataFileReady: $ORACULUM_HARVESTER_KAFKA_TOPIC_DATA_FILE_READY|oraculum.data_file_ready

harvester:
  consumerGroup: $ORACULUM_HARVESTER_KAFKA_CONSUMER_GROUP|oraculum-harvester
  requestTopic: $ORACULUM_HARVESTER_KAFKA_TOPIC_HARVESTER_REQUEST|oraculum.harvester.request
  dataDirectory: $ORACULUM_HARVESTER_DATA_DIRECTORY|/app/data
  exchangeDirectory: $ORACULUM_HARVESTER_EXCHANGE_DIRECTORY|/app/exchange
