"""add_t_analysis

Revision ID: 0004
Revises: 0003_fix_share_price_types
Create Date: 2024-08-01 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0004'
down_revision = '0003_fix_share_price_types'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correlation_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('analysis_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('report_md', sa.Text(), nullable=True),
    sa.Column('verdict', sa.String(), nullable=True),
    sa.Column('conviction', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_analysis_correlation_id', 't_analysis', ['correlation_id'], unique=True)
    op.create_index('ix_analysis_status_created', 't_analysis', ['status', 'created_at'], unique=False)
    op.create_index('ix_analysis_ticker_market_created', 't_analysis', ['ticker', 'market', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analysis_ticker_market_created', table_name='t_analysis')
    op.drop_index('ix_analysis_status_created', table_name='t_analysis')
    op.drop_index('ix_analysis_correlation_id', table_name='t_analysis')
    op.drop_table('t_analysis')
    # ### end Alembic commands ###