"""add_market_and_industry

Revision ID: 0005
Revises: 0004
Create Date: 2024-08-01 13:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_industry',
    sa.Column('industry_id', sa.String(), nullable=False),
    sa.Column('sector_name', sa.String(), nullable=False),
    sa.Column('industry_name', sa.String(), nullable=False),
    sa.Column('statement_template', sa.String(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('industry_id')
    )
    op.create_table('t_market',
    sa.Column('market_id', sa.String(), nullable=False),
    sa.Column('market_name', sa.String(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('market_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_market')
    op.drop_table('t_industry')
    # ### end Alembic commands ###
