"""create run_log table

Revision ID: 1234567890ab
Revises:
Create Date: 2024-05-07 10:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "1234567890ab"
down_revision: Union[str, None] = "9b3e2f7c1a6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "t_ingestion_run_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("run_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("file_checksum", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("loaded_rows", sa.Integer(), nullable=False),
        sa.Column("merged_rows", sa.Integer(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("error_text", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "dataset", "run_id", "file_checksum", name="uq_run_log_idempotency"
        ),
    )
    op.create_index(
        op.f("ix_t_ingestion_run_log_dataset"),
        "t_ingestion_run_log",
        ["dataset"],
        unique=False,
    )
    op.create_index(
        op.f("ix_t_ingestion_run_log_run_id"),
        "t_ingestion_run_log",
        ["run_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_t_ingestion_run_log_run_id"), table_name="t_ingestion_run_log"
    )
    op.drop_index(
        op.f("ix_t_ingestion_run_log_dataset"), table_name="t_ingestion_run_log"
    )
    op.drop_table("t_ingestion_run_log")
    # ### end Alembic commands ###
